
import { Product } from './types';

export const DUMMY_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Mechanical Gaming Keyboard',
    description: 'Ultra-responsive RGB mechanical keyboard with tactile switches and premium aluminum top plate.',
    price: 129.99,
    category: 'Gaming',
    image: 'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?q=80&w=800&auto=format&fit=crop',
    rating: 4.8,
    specs: ['RGB Lighting', 'Tactile Brown Switches', 'Aluminum Frame'],
    seller_id: 'admin-id',
    seller_name: 'NexShop'
  },
  {
    id: '2',
    name: 'Logitech G Pro Wireless',
    description: 'The preferred mouse for esports professionals worldwide, featuring the HERO 25K sensor.',
    price: 99.99,
    category: 'Gaming',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=800&auto=format&fit=crop',
    rating: 4.9,
    specs: ['Lightspeed Wireless', 'HERO 25K Sensor', '80g Lightweight'],
    seller_id: 'admin-id',
    seller_name: 'NexShop'
  },
  {
    id: '3',
    name: 'Sony WH-1000XM5',
    description: 'Industry-leading noise canceling headphones with premium sound and crystal clear call quality.',
    price: 348.00,
    category: 'Audio',
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?q=80&w=800&auto=format&fit=crop',
    rating: 4.7,
    specs: ['30h Battery', 'LDAC Support', 'Multi-point Bluetooth'],
    seller_id: 'admin-id',
    seller_name: 'NexShop'
  },
  {
    id: '4',
    name: 'Ergonomic Office Chair',
    description: 'Premium mesh chair designed for 12+ hours of comfort with adjustable lumbar support.',
    price: 499.00,
    category: 'Workstation',
    image: 'https://images.unsplash.com/photo-1505797149-43b007664a3d?q=80&w=800&auto=format&fit=crop',
    rating: 4.6,
    specs: ['Adjustable Lumbar', '4D Armrests', 'Breathable Mesh'],
    seller_id: 'admin-id',
    seller_name: 'NexShop'
  },
  {
    id: '5',
    name: 'Samsung 32" Odyssey G7',
    description: '1000R curved gaming monitor with 240Hz refresh rate and QLED technology.',
    price: 699.99,
    category: 'Gaming',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=800&auto=format&fit=crop',
    rating: 4.5,
    specs: ['240Hz', '1ms response', 'QLED Technology'],
    seller_id: 'admin-id',
    seller_name: 'NexShop'
  },
  {
    id: '6',
    name: 'MacBook Pro 14"',
    description: 'The ultimate power machine for creators and pros with the M3 Pro silicon chip.',
    price: 1999.00,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=800&auto=format&fit=crop',
    rating: 4.9,
    specs: ['M3 Pro Chip', 'Liquid Retina XDR', '18GB RAM'],
    seller_id: 'admin-id',
    seller_name: 'NexShop'
  },
  {
    id: '7',
    name: 'Keychron Q1 Pro',
    description: 'Full aluminum custom wireless mechanical keyboard with QMK/VIA support.',
    price: 189.00,
    category: 'Workstation',
    image: 'https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=800&auto=format&fit=crop',
    rating: 4.8,
    specs: ['Gasket Mount', 'Double-shot PBT', 'Screw-in stabs'],
    seller_id: 'admin-id',
    seller_name: 'NexShop'
  },
  {
    id: '8',
    name: 'Blue Yeti Microphone',
    description: 'The gold standard for professional recording and streaming with multiple pattern modes.',
    price: 109.99,
    category: 'Audio',
    image: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?q=80&w=800&auto=format&fit=crop',
    rating: 4.4,
    specs: ['Tri-capsule array', 'Multiple patterns', 'USB connection'],
    seller_id: 'admin-id',
    seller_name: 'NexShop'
  },
  {
    id: '9',
    name: 'Apple Watch Ultra 2',
    description: 'The most rugged and capable Apple Watch ever, designed for adventure.',
    price: 799.00,
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1434493907317-a46b53b81822?q=80&w=800&auto=format&fit=crop',
    rating: 4.9,
    specs: ['Titanium Case', '36-hour Battery', 'Precision Dual-Freq GPS'],
    seller_id: 'admin-id',
    seller_name: 'NexShop'
  },
  {
    id: '10',
    name: 'DJI Mini 4 Pro',
    description: 'Advanced mini drone with omnidirectional obstacle sensing and 4K HDR video.',
    price: 759.00,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1507582020474-9a35b7d455d9?q=80&w=800&auto=format&fit=crop',
    rating: 4.8,
    specs: ['4K/60fps HDR', '34-min Flight Time', 'Omni Obstacle Sensing'],
    seller_id: 'admin-id',
    seller_name: 'NexShop'
  },
  {
    id: '11',
    name: 'Canon EOS R6 Mark II',
    description: 'High-performance full-frame mirrorless camera for professional photo and video.',
    price: 2499.00,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=800&auto=format&fit=crop',
    rating: 4.7,
    specs: ['24.2 MP Full-Frame', '4K 60p Video', 'Dual Pixel CMOS AF II'],
    seller_id: 'admin-id',
    seller_name: 'NexShop'
  },
  {
    id: '12',
    name: 'Audioengine A2+ Speakers',
    description: 'Premium desktop speakers with high-fidelity sound and versatile connections.',
    price: 269.00,
    category: 'Audio',
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?q=80&w=800&auto=format&fit=crop',
    rating: 4.6,
    specs: ['Built-in Power Amps', 'Aramid Fiber Woofers', 'Silk Dome Tweeters'],
    seller_id: 'admin-id',
    seller_name: 'NexShop'
  },
  {
    id: '13',
    name: 'Meta Quest 3',
    description: 'The world\'s most popular VR headset, now with breakthrough mixed reality.',
    price: 499.99,
    category: 'Gaming',
    image: 'https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?q=80&w=800&auto=format&fit=crop',
    rating: 4.8,
    specs: ['Mixed Reality Passthrough', 'Pancake Lenses', 'Snapdragon XR2 Gen 2'],
    seller_id: 'admin-id',
    seller_name: 'NexShop'
  },
  {
    id: '14',
    name: 'Elgato Stream Deck MK.2',
    description: 'Evolutionary interface for controlling apps and tools with 15 customizable LCD keys.',
    price: 149.99,
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1634842133099-281a8b9e69ca?q=80&w=800&auto=format&fit=crop',
    rating: 4.7,
    specs: ['15 LCD Keys', 'Customizable Faceplate', 'Detachable Stand'],
    seller_id: 'admin-id',
    seller_name: 'NexShop'
  },
  {
    id: '15',
    name: 'Anker Prime Charging Station',
    description: 'Powerful 6-port desktop charger with smart power allocation and GaN technology.',
    price: 79.99,
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1610492421943-41a6b4b4594a?q=80&w=800&auto=format&fit=crop',
    rating: 4.5,
    specs: ['240W Total Output', '6 USB Ports', 'ActiveShield 2.0'],
    seller_id: 'admin-id',
    seller_name: 'NexShop'
  },
  {
    id: '16',
    name: 'Philips Hue Starter Kit',
    description: 'The foundation of your smart home lighting with millions of colors and shades.',
    price: 199.00,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1550524514-9636edec33c7?q=80&w=800&auto=format&fit=crop',
    rating: 4.4,
    specs: ['3 Color Bulbs', 'Hue Bridge Included', 'Voice Control Ready'],
    seller_id: 'admin-id',
    seller_name: 'NexShop'
  }
];
